# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mbmdrCpp <- function(pred_type, input_data, response, variable_names, order, alpha, max_results, top_results, num_threads, verbose) {
    .Call('MBMDRClassifieR_mbmdrCpp', PACKAGE = 'MBMDRClassifieR', pred_type, input_data, response, variable_names, order, alpha, max_results, top_results, num_threads, verbose)
}

